namespace Addons
{
    public partial class Addon : IAddon
    {
        public void CreateMcAddonFile()
        {
            McAddonManager.CreateMcAddonFile();

            Console.Clear();
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write($"All addon files were created successfully:");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.WriteLine($"/com.mojang/{Name}.mcaddon\n");
            Console.ResetColor();
            Console.WriteLine("This addon was generated by the Custom Addon Compiler created by Jayme Fernandes.");
            Console.WriteLine("If you have any questions or need support, feel free to reach out through the GitHub repository.\n");
            Console.ForegroundColor = ConsoleColor.Green;
            Console.Write("[GitHub Repository]");
            Console.ForegroundColor = ConsoleColor.Blue;
            Console.WriteLine("(https://github.com/JaymeFernandes/Addons_Compiler)\n\n\n");
        }


        public IBehaviorPack? Behavior { get; set; }
        public IResourcePack? Resource { get; set; }
        public string Name { get; private set; } = "";
        public string Description { get; private set; } = "";
        public List<int> Version { get; private set; } = new List<int> { 3, 0, 0 };
        public List<int> MinVersion { get; private set; } = new List<int> { 1, 8, 0 };
    }
}
