using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Addons.Services.FileManager
{
    internal class ReadMe
    {
        internal const string Read = @"## 🌟 Custom Minecraft Bedrock Addon 🌟

This addon was generated using the Custom Addon Compiler for Minecraft Bedrock Edition.

## 📖 About

This addon includes custom items, blocks, and behaviors designed to enhance your Minecraft experience. It was automatically compiled from C# code using our Custom Addon Compiler.

## 🛠️ Compiler

The Custom Addon Compiler is a tool designed to streamline the creation of Minecraft Bedrock addons by converting C# code into the required JSON files and structures. It is aimed at developers who prefer coding in C# and want to create complex addons with ease.

## 📂 Repository

For more information, updates, and to contribute, please visit the GitHub repository:

🔗 [GitHub Repository](https://github.com/JaymeFernandes/Addons_Compiler)

## 👨‍💻 Author

This addon was generated by the Custom Addon Compiler created by Jayme Fernandes. If you have any questions or need support, feel free to reach out through the GitHub repository.

## 📜 License

This addon and the Custom Addon Compiler are open-source projects. For more details, please refer to the LICENSE file in the GitHub repository.

✨ Happy crafting! ✨
";
    }
}