using System;
using System.IO;


namespace Addons
{
    /// <summary>
    /// Represents the hand types for rendering.
    /// </summary>
    public enum HandTypes
    {
        MainHand,
        OffHand
    }

    /// <summary>
    /// Represents the view types for rendering.
    /// </summary>
    public enum ViewTypes
    {
        FirstPerson,
        ThirdPerson
    }

    public enum SaturationModifier
    {
        Low,
        Normal,
        High
    }


    public enum AddonType
    {
        Data,
        Resources,
        Scripting,
        Interface,
        SkinPack,
        WorldTemplate
    }

    public enum TextureType
    {
        Items,
        Terrain,
        Entity,
        Environment,
        Gui,
        Misc,
        Particles
    }

    public static class MinecraftColor
    {
        public const string Black = "§0";
        public const string Dark_blue = "§1";
        public const string Dark_green = "§2";
        public const string Dark_aqua = "§3";
        public const string Dark_red = "§4";
        public const string Dark_purple = "§5";
        public const string Gold = "§6";
        public const string Gray = "§7";
        public const string Dark_gray = "§8";
        public const string Blue = "§9";
        public const string Green = "§a";
        public const string Aqua = "§b";
        public const string Red = "§c";
        public const string Light_purple = "§d";
        public const string Yellow = "§e";
        public const string White = "§f";
        public const string Minecoin_gold = "§g";
        public const string Material_quartz = "§h";
        public const string Material_iron = "§i";
        public const string Material_netherite = "§j";
        public const string Material_redstone = "§m";
        public const string Material_copper = "§n";
        public const string Material_gold = "§p";
        public const string Material_emerald = "§q";
        public const string Material_diamond = "§s";
        public const string Material_lapis = "§t";
        public const string Material_amethyst = "§u";
    }

    public static class MinecraftFormatting
    {
        public const string Obfuscated = "§k";
        public const string Bold = "§l";
        public const string italic = "§o";
        public const string reset = "§r";
    }


    internal class ReadMe
    {
        internal const string Read = @"## 🌟 Custom Minecraft Bedrock Addon 🌟

This addon was generated using the Custom Addon Compiler for Minecraft Bedrock Edition.

## 📖 About

This addon includes custom items, blocks, and behaviors designed to enhance your Minecraft experience. It was automatically compiled from C# code using our Custom Addon Compiler.

## 🛠️ Compiler

The Custom Addon Compiler is a tool designed to streamline the creation of Minecraft Bedrock addons by converting C# code into the required JSON files and structures. It is aimed at developers who prefer coding in C# and want to create complex addons with ease.

## 📂 Repository

For more information, updates, and to contribute, please visit the GitHub repository:

🔗 [GitHub Repository](https://github.com/YourUsername/CustomAddonCompiler)

## 👨‍💻 Author

This addon was generated by the Custom Addon Compiler created by Jayme Fernandes. If you have any questions or need support, feel free to reach out through the GitHub repository.

## 📜 License

This addon and the Custom Addon Compiler are open-source projects. For more details, please refer to the LICENSE file in the GitHub repository.

✨ Happy crafting! ✨
";
    }

}
